oracle-samples/oci-data-science-ai-samples

model-deployment-examples/LightGBM/score.py
model-deployment-examples/LightGBM_ONNX/score.py
model-deployment-examples/NLP_TF/score.py
model-deployment-examples/PyTorch_ResNet152/score.py
model-deployment-examples/RandomForest/score.py
model-deployment-examples/SklearnLR/score.py
model-deployment-examples/TFKeras/score.py
model-deployment-examples/TF_ResNet152/score.py
model-deployment-examples/XGBoost/score.py
model-deployment-examples/XGBoost_ONNX/score.py

record_latency comes from here https://bitbucket.oci.oraclecorp.com/projects/ODSC/repos/model_deployment_testing/browse/deployment_testing/deploy_test/monitor.py#45 
I can copy this file over and it’s dependencies, but since it’s just for timing maybe better I just take it the reference to it all together. Making a new PR for that now

Review: removing record_latency references

---

labs/PiDay-2022-Vision/Lab-3-vision-rest.md

I'll add the rest of the updates today/by Monday morning.

Initial REST API Updates

---

data-wrangling/parquet-from-oss.ipynb

Simple notebook to read public datasets from object storage. Files are written in parquet. One or more larger files (400+ MB per file). 
Using pandas and ocifs. pyarrow is the backend engine.

Parquet example

---

labs/MLSummit21/notebooks/1-model-training.ipynb

When running the notebook as is, the following error is encountered when running all the module imports:
```
ModuleNotFoundError: No module named 'onnxconverter_common.auto_mixed_precision'
```
This can be fixed by running `pip install onnxconverter-common --upgrade`

Add onnxconverter-common install to fix import issues

---

model_deploy_examples/LightGBM_ONNX/runtime.yaml

Description
Follow up on ticket: https://jira.oci.oraclecorp.com/browse/ODSC-31141
This PR edits the LightGBM_ONNX model runtime.yaml file to use python version 3.7

LightGBM_ONNX_python_version_update

---

jobs/README.md
jobs/java/pom.xml
jobs/java/src/main/java/MLJobs.java
jobs/java/src/main/java/Test.java
jobs/java/src/main/java/TestDelete.java
jobs/java/src/main/java/job_java.java

- bump the Java OCI SDK version
- comply the code with the builder patter, remove deprecations, fix pom dependancies

Update the Jobs Java Client SDK examples

---

jobs/flask_job_monitor/job_monitor.py
jobs/flask_job_monitor/static/dashboard.js
jobs/flask_job_monitor/templates/job_run_template.html
jobs/flask_job_monitor/templates/run_workflow.html

A few updates on the job monitor app:
* Show job run configuration, including overwritten environment variables when viewing job YAML.
* Return json payload instead of plain text when there is an error.
* In the compartments dropdown list, show only the first level compartments if user does not have permission to list all sub-compartments.
* Redirect `/favicon.ico` to `www.oracle.com/favicon.ico`.
* Restrict `Run Workflow` feature to API Key authentication only.

Update Job monitor

---

distributed_training/train_gpt_with_pytorch_ddp.md

This tutorial shows how users can train GPT model on OCI Data Science using existing code from official PyTorch examples.

Add tutorial on Training GPT Model with PyTorch DDP

---

notebook_examples/pyspark-data_flow-application.ipynb

Jira: https://jira.oci.oraclecorp.com/browse/ODSC-43403
Removed the example of using `ads.dataflow.dataflow` module in ADS example notebooks. 
https://objectstorage.us-ashburn-1.oraclecloud.com/p/e2l-k6eYE0jzcpnOsEJop6RwsqaymZlLtbm9hfmWWvJyLF2hwtNkk6Dwsei3MOIe/n/ociodscdev/b/ming-dev/o/notebook_examples/pyspark-data_flow-application.html

Update ADS pyspark-dataflow-application-notebook

---

model_catalog_examples/notebook_examples/uploading_larger_artifact_oci_python_sdk.ipynb

This [blog post](https://blogs.oracle.com/ai-and-datascience/post/solution-for-timeout-error-while-uploading-larger-size-model-artifact) is outdated now but users are continuing to refer to it. Main issue:
The blog is referring users to this [example notebook](https://github.com/oracle/oci-data-science-ai-samples/blob/master/model_catalog_examples/notebook_examples/uploading_larger_artifact_oci_python_sdk.ipynb), in which the entire model is read into the memory and then passed into the OCI SDK. However, the correct way to avoid the timeout issue should be passing the “stream” or file-like object into the OCI Python SDK instead. There is no need to set timeout value except for really slow internet connection.

pass stream to create_model_artifact

---

model_catalog_examples/notebook_examples/uploading_larger_artifact_oracle_ads.ipynb

It is still showing the old way of using ADS to save the model (deprecated since 2.6.6), which is also reading the entire file before passing it into OCI SDK. This issue has been fixed in the [new framework specific way](https://accelerated-data-science.readthedocs.io/en/latest/user_guide/model_registration/quick_start.html) of saving models.

[ODSC-49121]update with the latest module

---

.pre-commit-scripts/check-copyright.py

Currently the `check-copyright.py` is checking all filenames contained in `sys.argv`. However, `sys.argv[0]` is the filename of the `check-copyright.py` script. We should not check this script. Especially when this script itself may fail the copyright check in the new year :) (like missing the 2024 copyright).

Update check-copyright.py to check only user modified files.

---

.github/workflows/test_check_copyright.yml

After merged https://github.com/oracle-samples/oci-data-science-ai-samples/pull/382 to main, gh actions added to main and any issues can be fixed and checked. This Pr is to fix any observed error in tests action for copyright pre-commit.
- fixed python-version in actions/setup-python@v4
Test action works as expected and copyright tests passed:
https://github.com/oracle-samples/oci-data-science-ai-samples/actions/runs/7478136881

Fixes to action yaml in tests for check_copyright pre-commit

---

ai-quick-actions/cli.md

This PR adds documentation along with examples on how users can access Aqua resources via ads CLI.

Add aqua cli documentation

---

LLM/deploy-llm-byoc.md

Removed reference to AQUA as this is a model deployment BYOC approach.  I want to make sure customer do not think this is something they can only do in AQUA.

remove reference to AQUA

---

notebook_examples/README.md
notebook_examples/index.json

After successfully merging `train-mysql-heatwave-deploy-xgboost.ipynb` in main branch, we noticed that the new notebook is not reflecting in the Notebook Explorer of OCI Data Science. The fix was identified to update the index.json and Readme.md file with the details on the new notebook.
Appreciate your review and approval. 
@darenr @mrDzurb

Updating Index.json and Readme.md file to reflect the new notebook train-mysql-heatwave-deploy-xgboost.ipynb

---

ai-quick-actions/fine-tuning-tips.md

Updating the AQUA fine-tuning tips to show dataset format example for fine-tuning mllama models.

Add dataset format for fine-tuning Mllama Model

---

ai-quick-actions/troubleshooting-tips.md

Added details to generally troubleshoot auth errors in AQUA. Added headers to allow us to throw errors from AQUA directly referencing solutions on the troubleshooting page.
For example:
if error is 404, list_log_groups --> we directly link the troubleshooting page and the section "list log group" within the Authorization Errors section.

Corrected: Additional Details Added to Aqua Troubleshooting Documentation For Auth Errors

---

ai-quick-actions/ai-quick-actions-containers.md
ai-quick-actions/release-notes.md

Adding release notes for AQUA `v1.0.7` and `v1.0.6d`

Updating Aqua release notes

---

ai-quick-actions/troubleshooting-tips.md

On troubleshooting docs for AQUA, corrected model deployment watch command.

fixed model deployment watch command

---

model-deployment/multiple_inference_endpoints/openai_sdk_auth/README.md
model-deployment/multiple_inference_endpoints/openai_sdk_auth/local_custom_auth.py
model-deployment/multiple_inference_endpoints/openai_sdk_auth/local_custom_auth_streaming.py
model-deployment/multiple_inference_endpoints/openai_sdk_auth/oci_openai_auth/signer_auth_override.py

This new folder has examples for multiple inference client code snippets. 
Currently adding an example to show how we can call multiple inference OCI backed with OpenAI SDK (with OCI auth override)

Multiple inference example for openai sdk auth

---

ai-quick-actions/ai-quick-actions-containers.md

Updated the supported versions for vLLM and TGI. 
vLLM upgraded from 0.8.5.post1 -> 0.9.1
TGI upgraded from 2.0.1 -> 3.2.1

AQUA Readme Update
