- knowledge_base/001_No_Module_Named_ADS_Error_Fix.md
* Clarify instructions.
* Change the formatting to numbering instead of bullet points.
> Update article 001

- knowledge_base/002_TNS_Could_Not_Resolve_Connect_Identifier_Error_Fix.md
> Release 2021 07 15

- labs/MLSummit21/notebooks/2-model-deployment.ipynb
Fixed the auth issue with ADS in the deployment notebook.
> Setting auth to resource_principal for ads

- labs/PiDay-2022-Vision/Lab-3-vision-rest.md
@wprichard - if you can merge this then Mark will be taking over the Task 3.
> updated task 1 and task 2.

- jobs/flask_job_monitor/README.md
- jobs/flask_job_monitor/job_monitor.html
- jobs/flask_job_monitor/job_monitor.py
- jobs/flask_job_monitor/requirements.txt
Adding a Flask job monitor app. Users can use it to see job yaml, job run status and outputs.
> Add job monitor.

- distributed_training/artifacts/README.md
- distributed_training/notebooks/README.md
- distributed_training_notebooks/README.md
reorganize distributed training folder
> Dist training

- ai_services/anomaly_detection/data_preprocessing_examples/oci_data_flow_based_examples/Fixed_window_batching.md
- ai_services/anomaly_detection/data_preprocessing_examples/oci_data_flow_based_examples/date_time_conversion.md
- ai_services/anomaly_detection/data_preprocessing_examples/oci_data_flow_based_examples/example_code/sliding_window_aggregation.py
- ai_services/anomaly_detection/data_preprocessing_examples/oci_data_flow_based_examples/feature_normalization.md
- ai_services/anomaly_detection/data_preprocessing_examples/oci_data_flow_based_examples/sharding.md
- ai_services/anomaly_detection/data_preprocessing_examples/oci_data_flow_based_examples/sliding_window_aggregation.md
- ai_services/anomaly_detection/data_preprocessing_examples/oci_data_flow_based_examples/temporal_differencing.md
Testing: Verified output using test file ai_services/anomaly_detection/data_preprocessing_examples/sample_datasets/univariate_time_series.csv
> Added min/max/first operations to Sliding Window Aggregation

- distributed_training/notebooks/README.md
- distributed_training/notebooks/dask.md
- distributed_training/notebooks/horovod.md
- distributed_training/notebooks/pytorch.md
Added README files for Horovod, Dask and Pytorch. 
Added README file for getting started steps: Network and Policies configuration + ads opctl installtion
> Distributed Training: added READMES 

- jobs/flask_job_monitor/README.md
- jobs/flask_job_monitor/config.json
- jobs/flask_job_monitor/job_monitor.py
- jobs/flask_job_monitor/templates/run_workflow.html
* Update Readme.
* Use config.json for users to set dir for loading YAML.
> Job monitor

- ai_services/anomaly_detection/data_preprocessing_examples/oci_data_flow_based_examples/README.md
- ai_services/anomaly_detection/data_preprocessing_examples/oci_data_flow_based_examples/example_code/parquet_to_csv.py
- ai_services/anomaly_detection/data_preprocessing_examples/oci_data_flow_based_examples/parquet_to_csv.md
add example for reading parquet file and converting it to CSV
> AD Preprocessing Samples: add parquet example

- .gitignore
- jobs/python/README.md
- jobs/python/job+samples/custom_conda.py
- jobs/python/job+samples/greeting-env-cmd.py
- jobs/python/job+samples/hello_world_env_cmd_rp_job.py
- jobs/python/job+samples/rp.py
- add rp and simple env. and cmd job example
> - fix readme

- distributed_training/README.md
- distributed_training/Tensorboard.md
- distributed_training/dask.md
- distributed_training/distributed_training_cmd.md
- distributed_training/horovod.md
- distributed_training/pytorch.md
- distributed_training/tensorflow.md
- improve formatting and wordings
> distributed training documentation improvements

- distributed_training/Troubleshooting.md
1. Minor format related changes.
2. Added 'known Issues' section.
> DT:added known issue to FAQ

- distributed_training/Troubleshooting.md
- distributed_training/dask.md
- distributed_training/horovod.md
- distributed_training/pytorch.md
- distributed_training/tensorflow.md
- jobs/byoc/job_logs.py
- jobs/flask_job_monitor/README.md
- jobs/java/src/main/java/MLJobs.java
- jobs/python/job+samples/rp.py
- jobs/python/job+samples/vault.py
- jobs/python/sdk/jobs.py
- jobs/python/sdk/mljobs.py
- jobs/zip+tar/zipped_python_job/utils/log.py
- fix the vault example and OCI API Key profile settings
- fix markdown formatting preventing properly coping the cli commands
> fix vault jobs examples, profile settings and formatting of the cli commands in dtv docs

- notebook_examples/pyspark-data_catalog-hive_metastore-data_flow.ipynb
- notebook_examples/pyspark-data_catalog-hive_metastore.ipynb
The readme is not updated. Has to be done in a separate PR. The readme generator creates a lot of diff though the changes are limited to the two files.
> Renamed files

- labs/dataflow_in_ds_fraud_detection/Credit Card Fraud detection example.ipynb
Signed-off: Emmanuel Leroy <emmanuel.leroy@oracle.com>
> fix spark_config issue when not provided

- distributed_training/README.md
- jobs/byoc/README.md
> improving documentation

- notebook_examples/pipelines-ml_lifecycle.ipynb
* Added ADS notebook example for OCI pipeline service [limited availability]
> Added example for OCI pipeline service[limited availability]

- notebook_examples/README.md
- notebook_examples/api_keys-authentication.ipynb
- notebook_examples/model_evaluation-with-ADSEvaluator.ipynb
- notebook_examples/pyspark-data_flow-application.ipynb
- notebook_examples/streaming-service-introduction.ipynb
- notebook_examples/visualizing_data-exploring_data.ipynb
- notebook_examples/xgboost-with-rapids.ipynb
6 notebooks has been renamed and a README file updated per that change
> renaming 6 notebooks

- .github/workflows/make_readme.yml
- action.yaml
Ads a GitHub action which automatically creates README.md. The action is triggered on change of *.ipynb or make_readme.py files in notebook_examples folder and after README file updated, commit it.
**Verification steps:**
1. If change to make_readme.py file has been done, or a change to *ipynb file has been done, the workflow would start. A small brown circle would appear next to the commit while workflow running:
A click on the circle opens the details:
2. It'll change to green check mark if workflow successfully finished:
3. If the notebook file has been renamed, but the blob still has a new name, the error will occur: 
4. If README file has been changed, git bot should auto commit that change:
> Git hub action readme

- .github/workflows/make_readme.yml
- actions/create_pr_action/action.yaml
- actions/make_readme/action.yaml
This PR adds 2 GitHub actions to be called from `make_readme.yml` workflow, which activates on push, pull request or can be triggered manually. Once the workflow is activated, the action in `actions/make_readme/action.yaml` will be called to run the `notebook_examples/make_readmy.py` script to update the `README.md`, then the action in `actions/create_pr_action/action.yaml` will create a PR with following set of steps:
1. Add changes to the README file by `git add ':/notebook_examples/README.md'`
2. Check if there are staged changes by `if [[ -z $CHANGED_FILES ]]; then`
3. If there are staged changes, checkout to the new branch `git checkout -b 'auto_update_readme'`
4. Commit the changes with `git commit -m 'README.md auto update'`
5. Push changes `git push --set-upstream origin …
> GitHub actions to auto update README and create PR

- .github/workflows/make_readme.yml
- actions/create_pr_action/action.yaml
- GitHub action for creating a README.md and a PR for it has been updated to run on master branch only. 
- The branch name for the branch that is being being created in order to make a pull request if README.md has changes has been updated with a timestamp to make it the branch name unique.
> GitHub action to auto create README.md updated to run on master branch only + timestamp

- .gitignore
- jobs/java/src/main/java/MLJobs.java
- jobs/ts+js/README.md
- jobs/ts+js/client.js
- jobs/ts+js/client_d.js
- jobs/ts+js/package.json
- adapt the code to the latest OCI SDK
- the latest OCI SDK updates to the latest jsonwebtoken
- the code now uses the Default Egress
> Upgrade to latest OCI SDK

- jobs/README.md
- jobs/custom_metrics/README.md
- jobs/custom_metrics/artifact/custom_metrics/custom_metrics_provider.py
- jobs/custom_metrics/artifact/custom_metrics/gpu_metrics_provider.py
- jobs/custom_metrics/artifact/custom_metrics/random_metrics_provider.py
- jobs/custom_metrics/artifact/entrypoint.sh
- jobs/custom_metrics/artifact/metrics_submitter.py
- jobs/custom_metrics/generate_csv.py
- jobs/custom_metrics/get_current_metrics.py
- jobs/custom_metrics/package_artifact.sh
- jobs/custom_metrics/query_helpers.py
Sample that illustrates how to built a job artifact that emits custom metrics, and how to query metric values.
@lyudmil-pelov / @mayoor / @mrDzurb / @qiuosier - it would be good if at least one of you can try to run this and confirm that it works on someone else's machine besides my own :)
> Jobs sample: Custom metrics

- .github/workflows/make_readme.yml
- actions/make_readme/action.yaml
- notebook_examples/make_readme.py
This PR updates make_readme.py script to write the notebook information to the index.json and updates the action to include index.json to commit and PR along with the README.py
The action has written 32 notebooks' info to the index.json:
Created a PR:
PR included index.json:
> make index.json

- notebook_examples/make_readme.py
Adds **size** and **time_created** fields in the **notebooks index.json**
> Adds create date info in the notebooks index json

- ai_services/anomaly_detection/sensitivity_auto_tuner/standalone_univariate/README.md
- ai_services/anomaly_detection/sensitivity_auto_tuner/standalone_univariate/requirements.txt
- ai_services/anomaly_detection/sensitivity_auto_tuner/standalone_univariate/sensitivity_auto_tuner.py
Anomaly Detection Service is releasing a new feature for Univariate models. This tools helps with tuning the sensitivity parameter to obtain desirable performance. More details in README.
> Sensitivity Auto Tuner tool for Standalone Univariate

- ai_services/language/java/pom.xml
- ai_services/language/java/readme.md
- ai_services/language/java/src/main/java/com/company/CustomModelsSample.java
- ai_services/language/java/src/main/java/com/company/Main.java
- ai_services/language/python/languageBatchSamples.py
- ai_services/language/python/languageCustomNERSample.py
- ai_services/language/python/languageCustomTXTCSample.py
- ai_services/language/python/languageTranslation.py
- ai_services/language/python/languagebasicdemo.py
- ai_services/language/python/languagebatchdemo.py
- ai_services/language/python/readme.md
- Updated Java Samples for Language 2.0
- Updated Python Samples for Language 2.0
- Fixed Circular dependency Issue
- Updated Java POM to use latest versions
- Updated Read.me
> Update samples for language 2.0

- notebook_examples/pypgx-graph_analytics-machine_learning.ipynb
The compatible conda pack listed is the only conda pack currently in production. The notebook runs with this pack. When a new pack is added in the next week the slug listed will be updated. The notebook works with both the production pack (21.4.4) and the pre-release pack (23.1.1)
> First version of PyPGX notebook

- model-deployment/containers/Triton/Deploy ONNX model on Triton.md
The formatting was added inside a code block which has no effect.
> Fix formatting in Deploy ONNX model on Triton file

- notebook_examples/README.md
- notebook_examples/index.json
Updated notebooks. Added new fairness notebook. All sources listed in file metadata
> Odsc 41036/update notebooks

- .gitleaks.toml
- .pre-commit-config.yaml
- .pre-commit-hooks.yaml
- .pre-commit-scripts/check-copyright.py
This PR add 3 pre-commit hooks:
1. copyright check - this was moved from bitbucket repository and trimmed to be "script" type instead of "python"
2. secrets - used gitleaks, but expanded with custom solution for generic secret
3. ocids - used gitleaks, special rule added with regex, which recognize real ocids
Jira: https://jira.oci.oraclecorp.com/browse/ODSC-42791 (more details about chosen solution in comments in this ticket)
- added check-copyright.py script
- added .pre-commit-hooks.yaml
- added .pre-commit-config.yaml
- added .gitleaks.toml
This run caught hardcoded passwords and ocids, only in notebok_examples folder AND missing copyright in py file:
```
(test_unitary) lrudenka@lrudenka-mac oci-data-science-ai-samples % git add . && git commit -m tests
Detect hardcoded …
```
> Add pre-commit hooks for ocids, copyright and secrets

- notebook_examples/README.md
- notebook_examples/index.json
- notebook_examples/onnx-integration-ads.ipynb
> Add onnx notebook

- notebook_lifecycle_scripts_examples/git-check-commit.sh
- notebook_lifecycle_scripts_examples/install-activate-conda.sh
- notebook_lifecycle_scripts_examples/sync-with-objectstorage.sh
Add in additional comment in the script for clarification
> Add in comment for install-activate-conda script

- model-deployment/api-gateway-proxy/Readme.md
- model-deployment/api-gateway-proxy/func.py
- model-deployment/api-gateway-proxy/func.yaml
- model-deployment/api-gateway-proxy/requirements.txt
API GW fronting Model deployment endpoint
> API GW fronting Model deployment endpoint

- LLM/Quantization/readme.md
- LLM/readme.md
Added LLM folder to curate all LLM articles
Added quantization sample.
> LLM folder and quantization sample

- notebook_lifecycle_scripts_examples/install_pyspark_conda_create_notebook.sh
Add in script to do part of set up for customers using data science notebook to work with data flow
> Add in script to set up notebook to use data flow

- ai-quick-actions/model-deployment-tips.md
This PR includes the following:
1. Updated header and use sseclient for python streaming example
2. Add java example for inference
> Update Model Deployment Inference example

- ai-quick-actions/model-deployment-tips.md
Updated the readme as per @mrDzurb's comments.
> Update model deployment tips

- ai-quick-actions/model-deployment-tips.md
Adds a disclaimer that oci-cli does not support streaming response.
> Update AQUA MD page 

- ai-quick-actions/policies/README.md
fix the links in the AI Quick Action policies readme
> fix broken links in policies page

- ai-quick-actions/policies/README.md
Update the policies page to add note to use terraform script even if user already has policies set up to use Data Science service
> Update policies md

- ai-quick-actions/README.md
- ai-quick-actions/policies/README.md
Improved the policy section of the AQUA documentation.
Added a section explaining how to setup all required policies manually.
> Improved the policy section of the AQUA documentation

- ai-quick-actions/policies/README.md
Add in detail that an admin in the tenancy needs to run the ORM script to set up policies
> Add info that admin in the tenancy needs to run the ORM stack

- ai-quick-actions/README.md
- ai-quick-actions/deploy-with-smc.md
- ai-quick-actions/policies/README.md
blog post to show how to deploy the Japanese ELYZA model with SMC on Data Science
> add SMC with ELYZA

- ai-quick-actions/README.md
- ai-quick-actions/llama3-with-smc.md
Mini Blog showing how to deploy LLama3 with Ai Quick Actions SMC (service managed container)
> Daren llama3 blog

- ai-quick-actions/ssh-notebook-session.md
Adds a guide on how to SSH into the DSC Notebook Session.
> Adds a guide on how to SSH into the DSC Notebook Session.

- model-deployment/containers/nim/Dockerfile
- model-deployment/containers/nim/README.md
- model-deployment/containers/nim/start.sh
NIM implementation with llama3 on OCI Data Science
> NIM implementation with llama3 on OCI Data Science

- LLM/deploy-llama3.1.md
@darenr I have removed the service managed container mention.
> Remove mention of SMC

- model-deployment/containers/nim/Dockerfile
- model-deployment/containers/nim/README.md
> File execution permission

- ai-quick-actions/multimodal-models-tips.md
Add a place holder to show how to use multimodal models
> add multimodal place holder

- ai-quick-actions/fine-tuning-tips.md
New updates in the AI Quick Action supports new formats for fine-tuning.
> Update tips for fine-tuning dataset

- LLM/embedding/deploy-embedding-model-tei.md
Fixed an incorrect tag added to docker tag command.
> Fix incorrect tag param in documentation

- ai-quick-actions/fine-tuning-tips.md
- ai-quick-actions/model-deployment-tips.md
The PR adds instructions to show the ability of user to update either deployment or fine-tuning config json for custom models that can be deployed via AI Quick Actions.
> Advanced deployment and fine-tuning config options

- ai-quick-actions/register-tips.md
This PR updates the registration tips for embedding model via both vLLM or TEI inference containers.
> Update registration tips for embedding model

- ai-quick-actions/policies/README.md
- ai-quick-actions/policies/terraform/iam.tf
This PR is intended to add MD policies for OCIR access for custom TEI container.
> Adding MD policies for OCIR access

- ai-quick-actions/cli-tips.md
- ai-quick-actions/model-deployment-tips.md
This PR adds the following:
- Update the AI Quick Actions CLI commands documentation and examples.
- Python example to access `v1/chat/completions` endpoint.
> Update AI Quick Actions documentation

- .gitignore
- ai-quick-actions/model-deployment-tips.md
- ai-quick-actions/model-deployment-tool-calling-tips.md
Updates the AQUA documentation to demonstrate the use of tool calling with the Llama 3.3 model on the latest SMC container.
> Adds AQUA MD VLLM tool calling tips

- ai-quick-actions/model-deployment-tool-calling-tips.md
Enhance AQUA tool calling tips
> Enhance AQUA tool calling tips

- ai-quick-actions/README.md
- ai-quick-actions/release-notes.md
This pull request adds a new `release-notes.md` file that consolidates the release notes for AI Quick Actions from various Oracle release pages.
> Adds AQUA release notes page.

- LLM/AutoGen/AutoGenFunctionCalling.ipynb
The notebook shows how to use register OCI generative AI client with AutoGen using ADS, along with a simple function calling example to do currency exchange.
> Add notebook example for using AutoGen with OCI.

- ai-quick-actions/model-deployment-tips.md
Update AQUA client documentation to Support `/predictWithResponseStream` Endpoint
> [AQUA] Update AQUA client documentation to Support predictWithResponseStream Endpoint

- ai-quick-actions/ai-quick-actions-containers.md
Updated ai-quick-actions-containers.md with latest supported versions
> Updated ai-quick-actions-containers.md with latest supported versions

- model-deployment/mcp-servers/stateful-python-example-server/Dockerfile
- model-deployment/mcp-servers/stateful-python-example-server/README.md
- model-deployment/mcp-servers/stateful-python-example-server/inference.py
- model-deployment/mcp-servers/stateful-python-example-server/mcp_simple_streamablehttp/__main__.py
- model-deployment/mcp-servers/stateful-python-example-server/mcp_simple_streamablehttp/event_store.py
- model-deployment/mcp-servers/stateful-python-example-server/mcp_simple_streamablehttp/server.py
- model-deployment/mcp-servers/stateful-python-example-server/mcp_simple_streamablehttp/test.py
- model-deployment/mcp-servers/stateful-python-example-server/model-deplyment.py
- model-deployment/mcp-servers/stateful-python-example-server/pyproject.toml
Stateful MCP python example with inferencing payloads
> Stateful MCP python example with inferencing payloads

- ai-quick-actions/policies/README.md
> Update Documentation for AI Quick Actions Setup and Policy Configuration

- ai-quick-actions/release-notes.md
This PR is intended to updates AQUA release notes about the multi model deployment support in AQUA UI.
> Updating AQUA release notes

- ai-quick-actions/README.md
- ai-quick-actions/time-series-forecasting/README.md
[ODSC-74153](https://jira.oci.oraclecorp.com/browse/ODSC-74153)
> Documentation added for aqua time-series models

- model-deployment/containers/nim/README-vanilla-containers.md
- model-deployment/diffusion-models/bentoml/Readme.MD
Readme updates for diffusion model
> Readme updates for diffusion model

- ai_services/vision/python/stream-video/README.md
- ai_services/vision/python/stream-video/stream_video_demo.py
> Update Stop Stream
